name: "Run checks: all modules"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Tests - Stage
        run: |
          cd backend
          cd newsfeed-platform
          ./gradlew test
        

      - name: Run Build
        run: |
          cd backend
          cd newsfeed-platform
          ./gradlew build
 
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate and Publish newsfeedcrawler image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t norcodes/newsfeed-crawler:$IMAGE_TAG ./backend/newsfeed-platform/api/newsfeed-crawler
          echo "Pushing Image"
          docker push norcodes/newsfeed-crawler:$IMAGE_TAG
  
